name: Build, test and release

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: SonarQube scan
        # This step only runs on pushes to the 'develop' branch
        if: github.ref == 'refs/heads/develop'
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

  release:
    name: Create GitHub release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist

      - name: Create tarball
        run: tar -czvf release-${{ github.ref_name }}.tar.gz -C dist .

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-*.tar.gz"
          generateReleaseNotes: true
          makeLatest: true
          tag: ${{ github.ref_name }}

  publish-gpr:
    name: Publish to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for GPR
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@${{ github.repository_owner }}"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to GPR
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
